### ISSUE TITLE
error

### ISSUE THREAD

**Issue by runescapejon** [prettydude/F3Name#7] opened 2019-01-14 13:25 UTC
https://pastebin.com/raw/fxKCwQKc

I have a fork of bungeecord im not sure if this is the cause but i connect with 1.13.2 and i got this error it seem to be something with LuckPerms

Yeap it's luckperms not the fork of bungeecord tested

**Comment by zubiden** [comment] 2019-01-14 15:06
Thanks for reporting! I'm glad that you use my plugin 😄 

And the error... Strange, seems that LP have only 1 group (I thought that I tested that case :/).
Try this version:
(GitHub doesn't allow .jar files, unzip)
[F3Name-zipped.zip](https://github.com/prettydude/F3Name/files/2755671/F3Name-zipped.zip)

**Comment by runescapejon** [comment] 2019-01-14 15:10
https://pastebin.com/raw/Skcdbqjr

Thanks for getting back to me. Here is the error from testing the jar

**Comment by zubiden** [comment] 2019-01-14 19:50
Well... I hope fixed now.
[F3Name-zipped.zip](https://github.com/prettydude/F3Name/files/2756808/F3Name-zipped.zip)

If it's also don't work, can you provide information about your LuckPerms group configuration?

**Comment by runescapejon** [comment] 2019-01-15 03:01
Error > https://pastebin.com/raw/iKKnsFnZ  all of my groups > https://luckperms.github.io/editor/#UBqUeNl7s7

**Comment by zubiden** [comment] 2019-01-15 21:01
Well... Copied your user permissions (default group for global, and * for bungee and vanilla), but I can't reproduce it.  
![image](https://user-images.githubusercontent.com/19638254/51209447-e695d780-1918-11e9-891d-9b58cc5440cd.png)

I'll try more tomorrow.

**Comment by zubiden** [comment] 2019-01-15 21:01
> Thanks for reporting! I'm glad that you use my plugin 😄
> 
> And the error... Strange, seems that LP have only 1 group (I thought that I tested that case :/).
> Try this version:
> (GitHub doesn't allow .jar files, unzip)
> [F3Name-zipped.zip](https://github.com/prettydude/F3Name/files/2755671/F3Name-zipped.zip)

Tested with that version (rolled up last change)

**Comment by runescapejon** [comment] 2019-01-15 23:28
@prettydude I had sometime to think and debug about this issue and i found a way to reproduce the error it seem if you have inheritance in default for example in the web editor under default group if you have `group.test` and then save it and put it under luckperms the your plugin will break because default shouldn't have inheritance this was my mistake you can close the issue if you like but thank you very much

**Comment by runescapejon** [comment] 2019-01-15 23:43
oh update on that it seem if any groups has inheritance the plugin will break

EDIT:
For example you have a donator rank called vip and want to inheritance default well you can under luckperms but F3Name plugin will break with the errors

**Comment by zubiden** [comment] 2019-01-17 19:58
> @prettydude I had sometime to think and debug about this issue and i found a way to reproduce the error it seem if you have inheritance in default for example in the web editor under default group if you have `group.test` and then save it and put it under luckperms the your plugin will break because default shouldn't have inheritance this was my mistake you can close the issue if you like but thank you very much

Found the problem! (But it's about group selecting, not your exception. I just can't reproduce it)
I'll rewrite that method tomorrow and give you to test. I hope it'll fix your issue.

**Comment by zubiden** [comment] 2019-01-18 19:38
[F3Name-zipped.zip](https://github.com/prettydude/F3Name/files/2774287/F3Name-zipped.zip)
Another attempt to fix your exception

**Comment by runescapejon** [comment] 2019-01-18 19:57
https://pastebin.com/8pMfyyxY
i had look into the luckperms a bit more on the group inheritance and it seem if the any groups are inheriting something that does not exist it push this error that we been having for example i have default group and i have default inheritance to vip group and i do not have vip group created it produce this error. I had clean out of all my luckperms and took out groups inheritance if the group had been deleted.

**Comment by zubiden** [comment] 2019-01-20 15:10
> if the any groups are inheriting something that does not exist it push this error that we been having for example i have default group and i have default inheritance to vip group and i do not have vip group created it produce this error.

Seems that LuckPerms recognizes every `group.ANY_WORD` permission as a group, even if it not exits. Quite unexpected behavior, but can be reasonable for LP API. (I think they need to edit their tutorial 😄)

Added additional check for non-existing groups. If everything works fine, I'm going to release this fix today.
[F3Name-zipped.zip](https://github.com/prettydude/F3Name/files/2776737/F3Name-zipped.zip)

**Comment by runescapejon** [comment] 2019-01-20 15:44
Yes it's fixed <3 thank you so much

**Comment by zubiden** [comment] 2019-01-20 18:30
Good to know. 👍 
I'm releasing it.

**Closed as completed by zubiden** 2019-01-20 18:30 UTC
